import type { GwynethAppsPageData } from "@/content/types";

export const gwynethAppsPageData: GwynethAppsPageData = {
  id: 1,
  hero_title: "Explore the Taiko Gwyneth Ecosystem",
  hero_about_suptitle: "About ecosystem",
  hero_about_text:
    "Join a supportive, collaborative ecosystem of innovation and build the future of Ethereum.",
  hero_about_btn: {
    id: 1,
    name: "Submit your project",
    link: "/grant-program",
    variant: "primary",
    newTab: false,
    disabledArrow: false,
  },
  hero_dapps: {
    id: 1,
    name: "DAPPS",
    value: "90+",
    icons: [
      "https://energized-luck-6459305596.media.strapiapp.com/ait_protocol_afd4aa8964.png",
      "https://energized-luck-6459305596.media.strapiapp.com/alphamint_27a5c1d2c2.png",
      "https://energized-luck-6459305596.media.strapiapp.com/apus_network_06eb367788.png",
      "https://energized-luck-6459305596.media.strapiapp.com/automata_d9d2f21ff4_78f4076e33.jpg",
      "https://energized-luck-6459305596.media.strapiapp.com/bitget_wallet_8a5b1aaa05.png",
      "https://energized-luck-6459305596.media.strapiapp.com/blazepay_c4e87ba9bd_019f2d48e7.jpg",
      "https://energized-luck-6459305596.media.strapiapp.com/blockpi_528ef6c5d3.png",
      "https://energized-luck-6459305596.media.strapiapp.com/blockscout_a3fdd113f2.svg",
    ],
  },
  disclaimer_title: "Disclaimer",
  disclaimer_text:
    "Be cautious when using third-party applications. Applications listed are provided for information without recommendation or endorsement. Your security and privacy are important, so research thoroughly before engaging with third-party applications. We are not responsible for any risks or losses associated with the use of any third-party offerings. Proceed at your own discretion.",
  disclaimer_active: true,
  apps_list: [
    {
      id: 33,
      name: "AIT Protocol",
      text: "The first Web3 data infrastructure focusing on AI data annotations",
      type: "Testnet",
      active: false,
      icon: "https://energized-luck-6459305596.media.strapiapp.com/ait_protocol_afd4aa8964.png",
      categories: ["Testnet"],
      url: "",
    },
    {
      id: 34,
      name: "Alphamint",
      text: "Multichain NFT marketplace to create, sell and buy ERC-721 tokens.",
      type: "Testnet",
      active: false,
      icon: "https://energized-luck-6459305596.media.strapiapp.com/alphamint_27a5c1d2c2.png",
      categories: ["NFT"],
      url: "",
    },
    {
      id: 35,
      name: "Apus Network",
      text: "Democratize compute through decentralized ZKP marketplace.",
      type: "Testnet",
      active: false,
      icon: "https://energized-luck-6459305596.media.strapiapp.com/apus_network_06eb367788.png",
      categories: ["Infrastructure", "Tool"],
      url: "",
    },
    {
      id: 36,
      name: "Automata Network",
      text: "Extend Ethereum\u2019s trust with optimistic rollups and zero-knowledge proofs via its Proof of Machinehood approach.",
      type: "Testnet",
      active: false,
      icon: "https://energized-luck-6459305596.media.strapiapp.com/automata_d9d2f21ff4_78f4076e33.jpg",
      categories: ["Infrastructure", "Tool"],
      url: "",
    },
    {
      id: 37,
      name: "Bitget Wallet",
      text: "Faster trading with your Web3 trading wallet of the future.",
      type: "Testnet",
      active: false,
      icon: "https://energized-luck-6459305596.media.strapiapp.com/bitget_wallet_8a5b1aaa05.png",
      categories: ["Wallet"],
      url: "",
    },
    {
      id: 38,
      name: "Blazepay",
      text: "Blazepay",
      type: "Testnet",
      active: false,
      icon: "https://energized-luck-6459305596.media.strapiapp.com/blazepay_c4e87ba9bd_019f2d48e7.jpg",
      categories: ["Defi"],
      url: "",
    },
    {
      id: 39,
      name: "BlockPI",
      text: "Distributed multi-chain acceleration layer. Solving the RPC requests congestion problem with infinite scalability.",
      type: "Testnet",
      active: false,
      icon: "https://energized-luck-6459305596.media.strapiapp.com/blockpi_528ef6c5d3.png",
      categories: ["Infrastructure"],
      url: "",
    },
    {
      id: 40,
      name: "Blockscout",
      text: "The multichain, configurable, open-source explorer unlocking comprehensive access to all blockchain data and features.",
      type: "Testnet",
      active: false,
      icon: "https://energized-luck-6459305596.media.strapiapp.com/blockscout_a3fdd113f2.svg",
      categories: ["Infrastructure"],
      url: "",
    },
  ],
};
